CREATE TABLE users
(
    id         INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username   VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    nickname   VARCHAR(255) NOT NULL DEFAULT 'no nickname',
    self_description VARCHAR(255) NOT NULL DEFAULT 'no self_description',
    avatar VARCHAR(255) COMMENT 'URL of the avatar',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
) CHARACTER SET utf8mb4;